game.splash("BONVINGUTS A PEPICLANDIA", "APRETA A PER CONEMÇAR I B PER DISPARAR")
effects.starField.startScreenEffect()
let mySprite = sprites.create(img`
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ..........fffff.
    ...ccc...ff1bbbf
    ..c1cccccccc1bbf
    ..c113333c1c11bf
    .c11333333cc11bf
    .c11c133331c11bf
    .c111cccc3c11bbf
    .f111111111ffbbf
    .ffcc11bbbbffbf.
    .fbbbbbbbbbbbbf.
    fbdbbbbbbbcbbbc.
    fdbbbbbbccbbbfbc
    fbbfcbbbbbcbbfbc
    fbfdccbbccbbfbbf
    ffddcccbbbccffbf
    .cddcccccccf..ff
    .cddcccccccf....
    ..cdbcccccf.....
    ...cbccccf......
    ....cfccf.......
    ...ffbbdc.......
    ..fbccbddc......
    .fbbcccbdc......
    fbbcffccbc......
    fbff...cb.......
    ff......cc......
    `, SpriteKind.Player)
controller.moveSprite(mySprite, 100, 100)
